name: speech_balloon
description: "This is a flutter widget that generates a simple speech bubble. I based it on the SpeechBubble that was originally created. This widget can display simple speech bubbles and reproduce speech bubbles with a border."
version: 0.0.1
homepage: https://s-tyd.com
repository: https://github.com/s-tyd/speech_balloon

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

plugin:
  platforms:
    android:
      package: com.example.speech_ballon
      pluginClass: SpeechBalloonPlugin
    ios:
      pluginClass: SpeechBalloonPlugin
